In [12]:
import pandas_datareader as pdr
import os

In [13]:
key = "5876a7de43a49430ea786fae7d255a3d103e60d8"

In [15]:
import yfinance as yf

# Fetch data for Apple (AAPL)
df = yf.download('AAPL', start='2020-01-01', end='2024-11-23')

# Display the first few rows of the DataFrame
print(df.head())

[*********************100%***********************]  1 of 1 completed

Price       Adj Close      Close       High        Low       Open     Volume
Ticker           AAPL       AAPL       AAPL       AAPL       AAPL       AAPL
Date                                                                        
2020-01-02  72.796013  75.087502  75.150002  73.797501  74.059998  135480400
2020-01-03  72.088287  74.357498  75.144997  74.125000  74.287498  146322800
2020-01-06  72.662712  74.949997  74.989998  73.187500  73.447502  118387200
2020-01-07  72.320976  74.597504  75.224998  74.370003  74.959999  108872000
2020-01-08  73.484352  75.797501  76.110001  74.290001  74.290001  132079200


In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1233 entries, 2020-01-02 to 2024-11-22
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   (Adj Close, AAPL)  1233 non-null   float64
 1   (Close, AAPL)      1233 non-null   float64
 2   (High, AAPL)       1233 non-null   float64
 3   (Low, AAPL)        1233 non-null   float64
 4   (Open, AAPL)       1233 non-null   float64
 5   (Volume, AAPL)     1233 non-null   int64  
dtypes: float64(5), int64(1)
memory usage: 67.4 KB


In [17]:
df.to_csv('AAPL.csv')

In [18]:
import pandas as pd

In [19]:
data = pd.read_csv('AAPL.csv')

In [20]:
data.head()

Price          Adj Close              Close               High  \
0      Ticker               AAPL               AAPL               AAPL   
1        Date                NaN                NaN                NaN   
2  2020-01-02  72.79601287841797   75.0875015258789   75.1500015258789   
3  2020-01-03  72.08828735351562  74.35749816894531   75.1449966430664   
4  2020-01-06  72.66271209716797  74.94999694824219  74.98999786376953   

                 Low               Open     Volume  
0               AAPL               AAPL       AAPL  
1                NaN                NaN        NaN  
2  73.79750061035156  74.05999755859375  135480400  
3             74.125   74.2874984741211  146322800  
4            73.1875  73.44750213623047  118387200

In [23]:
data.drop([0,1],inplace=True)

In [24]:
data.head()

Price          Adj Close              Close               High  \
2  2020-01-02  72.79601287841797   75.0875015258789   75.1500015258789   
3  2020-01-03  72.08828735351562  74.35749816894531   75.1449966430664   
4  2020-01-06  72.66271209716797  74.94999694824219  74.98999786376953   
5  2020-01-07  72.32097625732422  74.59750366210938   75.2249984741211   
6  2020-01-08   73.4843521118164  75.79750061035156  76.11000061035156   

                 Low               Open     Volume  
2  73.79750061035156  74.05999755859375  135480400  
3             74.125   74.2874984741211  146322800  
4            73.1875  73.44750213623047  118387200  
5  74.37000274658203  74.95999908447266  108872000  
6  74.29000091552734  74.29000091552734  132079200

In [26]:
df2 = data.reset_index()['Close']

In [28]:
df2.shape

(1233,)

In [30]:
df2

0         75.0875015258789
1        74.35749816894531
2        74.94999694824219
3        74.59750366210938
4        75.79750061035156
               ...        
1228    228.02000427246094
1229    228.27999877929688
1230                 229.0
1231    228.52000427246094
1232     229.8699951171875
Name: Close, Length: 1233, dtype: object

In [37]:
import numpy as np

In [39]:
from sklearn.preprocessing import MinMaxScaler
scalar = MinMaxScaler()
df1 = scalar.fit_transform(np.array(df2).reshape(-1,1))

In [40]:
df1

array([[0.1053011 ],
       [0.10125424],
       [0.10453883],
       ...,
       [0.95853374],
       [0.95587282],
       [0.96335666]])

In [41]:
training_size = int(len(df1)*0.65)
test_size = len(df1) - training_size

In [ ]:
train_data, test_data = df1[0:training_size,:], df1[training_size:len(df1),:1]

In [43]:
training_size, test_size

(801, 432)

In [ ]:
def create_dataset(dataset, time_step):
    dataX, dataY =[],[]
    for i in range(len(dataset)-time_step-1):
        a = dataset[i:(i+time_step),0]
        dataX.append(a)
        dataY.append(dataset[i+time_step, 0])
    return np.array(dataX), np.array(dataY)

In [45]:
time_step = 100
X_train, y_train = create_dataset(train_data, time_step)
X_test, y_test = create_dataset(test_data, time_step)

In [46]:
X_train

array([[0.1053011 , 0.10125424, 0.10453883, ..., 0.12816854, 0.1309958 ,
        0.12800224],
       [0.10125424, 0.10453883, 0.10258474, ..., 0.1309958 , 0.12800224,
        0.12991476],
       [0.10453883, 0.10258474, 0.10923707, ..., 0.12800224, 0.12991476,
        0.1301088 ],
       ...,
       [0.46565033, 0.46747974, 0.45949691, ..., 0.50622968, 0.49458804,
        0.49791425],
       [0.46747974, 0.45949691, 0.45594899, ..., 0.49458804, 0.49791425,
        0.52629756],
       [0.45949691, 0.45594899, 0.48172688, ..., 0.49791425, 0.52629756,
        0.54181972]])

In [47]:
y_train

array([0.12991476, 0.1301088 , 0.12967918, 0.13509807, 0.13716306,
       0.13962997, 0.13574945, 0.14847205, 0.15118841, 0.16578199,
       0.17804726, 0.15457002, 0.15858914, 0.16439609, 0.17699396,
       0.17631488, 0.17650893, 0.17372325, 0.18640427, 0.19702031,
       0.1880535 , 0.19467813, 0.17914214, 0.19043726, 0.19462268,
       0.1936664 , 0.1936664 , 0.20716515, 0.20555749, 0.21758714,
       0.21986005, 0.22078858, 0.21833554, 0.22709448, 0.23079482,
       0.22412862, 0.22304761, 0.23430116, 0.2267757 , 0.22828633,
       0.20374196, 0.20246691, 0.21463516, 0.20600099, 0.21591021,
       0.22228538, 0.27810965, 0.29295268, 0.29698567, 0.29918926,
       0.32047674, 0.30501008, 0.31396301, 0.29537802, 0.31552909,
       0.32661634, 0.32604811, 0.32438501, 0.32967918, 0.33048298,
       0.34471626, 0.37850464, 0.38675075, 0.38102695, 0.39043726,
       0.38205255, 0.38092997, 0.4043933 , 0.43288751, 0.41747625,
       0.35915737, 0.35960087, 0.31447579, 0.33942209, 0.31819

In [48]:
X_train.shape, y_train.shape

((700, 100), (700,))

In [49]:
X_train =X_train.reshape(X_train.shape[0], X_train.shape[1], 1)
X_test = X_test.reshape(X_test.shape[0], X_test.shape[1],1)

In [50]:
X_train.shape

(700, 100, 1)

In [53]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM

In [58]:
model = Sequential()
model.add(LSTM(50, return_sequences=True, input_shape=(100, 1)))
model.add(LSTM(50, return_sequences=True))
model.add(LSTM(50))
model.add(Dense(1))
model.compile(loss= 'mean_squared_error', optimizer ='adam', metrics = ['accuracy'])

f:\Deep learning Projects\DLenv\Lib\site-packages\keras\src\layers\rnn\rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [59]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm_3 (LSTM)                   │ (None, 100, 50)        │        10,400 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_4 (LSTM)                   │ (None, 100, 50)        │        20,200 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_5 (LSTM)                   │ (None, 50)             │        20,200 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            51 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 50,851 (198.64 KB)

 Trainable params: 50,851 (198.64 KB)

 Non-trainable params: 0 (0.00 B)

In [60]:
model.fit(X_train, y_train, validation_data=(X_test, y_test), batch_size=64, epochs=100, verbose=1)

Epoch 1/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 6s 178ms/step - accuracy: 0.0000e+00 - loss: 0.0914 - val_accuracy: 0.0030 - val_loss: 0.0500
Epoch 2/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 129ms/step - accuracy: 0.0000e+00 - loss: 0.0096 - val_accuracy: 0.0030 - val_loss: 0.0063
Epoch 3/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 127ms/step - accuracy: 0.0000e+00 - loss: 0.0050 - val_accuracy: 0.0030 - val_loss: 0.0368
Epoch 4/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 126ms/step - accuracy: 0.0000e+00 - loss: 0.0034 - val_accuracy: 0.0030 - val_loss: 0.0112
Epoch 5/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 122ms/step - accuracy: 0.0000e+00 - loss: 0.0026 - val_accuracy: 0.0030 - val_loss: 0.0136
Epoch 6/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 131ms/step - accuracy: 0.0000e+00 - loss: 0.0022 - val_accuracy: 0.0030 - val_loss: 0.0110
Epoch 7/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 132ms/step - accuracy: 0.0000e+00 - loss: 0.0019 - val_accuracy: 0.0030 - val_loss: 0.0078
Epoch 8/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 120ms/step - accuracy: 0.00

In [61]:
model.evaluate(X_test, y_test)

11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 7.6394e-04 - loss: 4.9544e-04


[0.0004725594772025943, 0.003021148033440113]

In [62]:
train_predict= model.predict(X_train)
test_predict =model.predict(X_test)

22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step


In [63]:
train_predict = scalar.inverse_transform(train_predict)
test_predict = scalar.inverse_transform(test_predict)

In [64]:
import math
from sklearn.metrics import mean_squared_error
math.sqrt(mean_squared_error(y_train, train_predict))


142.0363401303782

In [65]:
math.sqrt(mean_squared_error(y_test, test_predict))

197.07853594546668